home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name=app_name),
]

learn/urls.py
from django.urls import path
from . import views

app_name = 'learn'

urlpatterns = [
    path('', views.learn_index, name='learn_index'),
    path('<course_id>/', views.course_page, name='course_page'),
    path('<course_id>/<skill_id>/', views.skill_page, name='skill_page'),
]

stats/urls.py
from django.urls import path
from . import views

app_name = 'stats'

urlpatterns = [
	path('', views.stats_index, name='stats_index'),
	path('<course_id>/', views.stats_course, name='stats_course'),
	path('<course_id>/<skill_id>/', views.stats_skill, name='stats_skill'),
	path('skill_overall_stats', views.stats_skill_overall, name='stats_skill_overall'),
	path('skill_challenge_stats', views.stats_skill_challenge, name='stats_skill_challenge'),
]

studiocricket/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('learn/', include('learn.urls')),
    path('stats/', include('stats.urls')),
    path('tests/', include('tests.urls')),
    path('users/', include('users.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.home, name='home'),
]

home/models.py
from django.db import models

# Create your models here.

learn/models.py
from django.db import models


class Course(models.Model):
    course_name = models.CharField(max_length=100)
    course_image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.course_name


class Skillcategory(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    skillcategory_name = models.CharField(max_length=100)
    priority = models.IntegerField(default=0)

    def __str__(self):
        return self.skillcategory_name


class Skill(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    category = models.ForeignKey(Skillcategory, on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=100)
    skill_image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.skill_name


class Videocategory(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    videocategory_name = models.CharField(max_length=100)
    priority = models.IntegerField(default=0)

    def __str__(self):
        return self.videocategory_name


class Video(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    skill_category = models.ForeignKey(Skillcategory, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    category = models.ForeignKey(Videocategory, on_delete=models.CASCADE)
    video_name = models.CharField(max_length=100)
    video = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.video_name


class Challenge(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    challenge_name = models.CharField(max_length=100)
    priority = models.IntegerField(default=0)

    def __str__(self):
        return self.challenge_name

stats/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    image = models.ImageField(null=True, blank=True)
    phone_1 = models.CharField(max_length=10)
    phone_2 = models.CharField(max_length=10, null=True)
    dob = models.DateField(null=True)
    institute = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=250, null=True)
    pincode = models.IntegerField(default=0, null=True)
    discount = models.IntegerField(default=0)

    def __str__(self):
        return self.full_name

home/views.py
from django.shortcuts import render
#from django.http import HttpResponse

def home(request):
    return render(request, 'home/home.html')
# Create your views here.

learn/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . models import Course, Skillcategory, Skill, Videocategory, Video, Challenge


def learn_index(request):
	courses = Course.objects.all()
	return render(request,'learn/learn.html', {'courses': courses})


def course_page(request, course_id):
	skills = Skill.objects.filter(course=course_id)
	return render(request, 'learn/course_page.html', {'skills': skills})


def skill_page(request, course_id, skill_id):
	videos = Video.objects.filter(skill=skill_id)
	return render(request, 'learn/skill_page.html', {'videos': videos})
# Create your views here.

stats/views.py
from django.shortcuts import render
from learn.models import Course, Skill
from users.models import Profile
from tests.models import Test, Testinputs
#from django.http import HttpResponse

def stats_index(request):
	courses = Course.objects.all()
	return render(request, 'stats/stats_index.html', {'courses': courses})

def stats_course(request, course_id):
	skills = Skill.objects.filter(course=course_id)
	return render(request, 'stats/stats_course.html', {'skills': skills})


def stats_skill(request, course_id, skill_id):
	user = request.user
	tests = Test.objects.filter(user=user)
	footwork = 0
	middle = 0
	bat_position = 0
	head_position = 0
	elbow_position = 0
	shoulder_line = 0
	ball_direction = 0
	count = 0
	for test in tests:
		test_skill = test.test_skill()
		if test_skill == int(skill_id):
			testinputs = Testinputs.objects.filter(test=test)
			for testinput in testinputs:
				count += 1
				if testinput.footwork == True:
					footwork += 1
				if testinput.middle == True:
					middle += 1
				if testinput.bat_position == True:
					bat_position += 1
				if testinput.head_position == True:
					head_position += 1
				if testinput.elbow_position == True:
					elbow_position += 1
				if testinput.shoulder_line == True:
					shoulder_line += 1
				if testinput.ball_direction == True:
					ball_direction += 1
	if count != 0:
		footwork_stat = (footwork/count)*100
		middle_stat = (middle/count)*100
		bat_position_stat = (bat_position/count)*100
		head_position_stat = (head_position/count)*100
		elbow_position_stat = (elbow_position/count)*100
		shoulder_line_stat = (shoulder_line/count)*100
		ball_direction_stat = (ball_direction/count)*100
		return render(request, 'stats/stats_skill.html', {'footwork_stat': footwork_stat, 'middle_stat': middle_stat,
			'bat_position_stat': bat_position_stat, 'head_position_stat': head_position_stat, 'elbow_position_stat': elbow_position_stat,
			'shoulder_line_stat': shoulder_line_stat, 'ball_direction_stat': ball_direction_stat})
	else:
		return render(request, 'stats/stats_skill.html', {'no_data': 'No sufficient Data'})


def stats_skill_overall(request):
	return render(request, 'stats/stats_skill_overall.html')


def stats_skill_challenge(request):
	return render(request, 'stats/stats_skill_challenge.html')

users/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return HttpResponse("Home page")
# Create your views here.

templates/home/home.html
{% extends 'studiocricket/base.html' %}
{% block body %}
<h1>Home page</h1>
{% endblock %}

templates/learn/course_page.html
{% extends 'studiocricket/base.html' %}
{% block body %}
<h1 style="text-align: center;">{{skills.0.course}} course page</h1>
<!-- {% for skill in skills %}
	<h3><a href='{% url 'learn:skill_page' skill.course.id skill.id %}'>{{ skill.skill_name }}</a></h3>
{% endfor %} -->
<div class="container">
	<div class="row">
		{% for skill in skills %}
	   <div class="col-md-6">
		  <div class="card flex-md-row mb-4 shadow-sm h-md-250">
			 <div class="card-body d-flex flex-column align-items-start">
				<strong class="d-inline-block mb-2 text-primary">{{skill.course}}</strong>
				<h6 class="mb-0">
				   <a class="text-dark" href="{% url 'learn:skill_page' skill.course.id skill.id %}">{{ skill.skill_name }}</a>
				</h6>
				<div class="mb-1 text-muted small">Nov 12</div>
				<p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
				<a class="btn btn-outline-primary btn-sm" role="button" href="{% url 'learn:skill_page' skill.course.id skill.id %}">Continue reading</a>
			 </div>
			 <img class="card-img-right flex-auto d-none d-lg-block" alt="Thumbnail [200x250]" src="//placeimg.com/250/250/arch" style="width: 200px; height: 250px;">
		  </div>
	   </div>
	   {% endfor %}
	</div>
</div>

{% endblock %}

templates/learn/learn.html
{% extends 'studiocricket/base.html' %}
{% block body %}
<h1>Learn page</h1>
{% for course in courses %}
	<h3><a href='{% url 'learn:course_page' course.id %}'>{{ course.course_name }}</a></h3>
{% endfor %}

{% endblock %}

templates/learn/skill_page.html
{% extends 'studiocricket/base.html' %}
{% block body %}
<h1>Skill page</h1>
{% for video in videos %}
	<iframe width="560" height="315" src="https://www.youtube.com/embed/N74cnBa_Bmc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
{% endfor %}

{% endblock %}

templates/stats/stats_course.html
{% extends 'studiocricket/base.html' %}
{% block body %}
<h1>Stats Course Page</h1>
<p>Here you will see a list of skills categorized into skill sets to choose for stats of that particular skill</p>
{% for skill in skills %}
<h3><a href='{% url 'stats:stats_skill' skill.course.id skill.id %}'>{{skill.skill_name}}</a></h3>
{% endfor %}
{% endblock %}

templates/stats/stats_index.html
{% extends 'studiocricket/base.html' %}
{% block body %}
<h1>Stats Index Page</h1>
<p>Here you will see a list of courses to choose for stats of that particular course</p>
{% for course in courses %}
	<h3><a href='{% url 'stats:stats_course' course.id %}'>{{ course.course_name }}</a></h3>
{% endfor %}
{% endblock %}

templates/stats/stats_skill.html
{% extends 'studiocricket/base.html' %}
{% block body %}
<h1>Stats skill Page</h1>
<h2>Overall stats of the skill</h2>
{% if no_data %}
	<p>{{no_data}}</p>
{% else %}
	<h3>Foot work: {{footwork_stat}}</h3>
	<h3>Bat middling: {{middle_stat}}</h3>
	<h3>Bat swing: {{bat_position_stat}}</h3>
	<h3>Head position: {{head_position_stat}}</h3>
	<h3>Elbow position: {{elbow_position_stat}}</h3>
	<h3>Shoulder line: {{shoulder_line_stat}}</h3>
	<h3>Ball direction: {{ball_direction_stat}}</h3>
{% endif %}
{% endblock %}

templates/stats/stats_skill_challenge.html
{% extends 'studiocricket/base.html' %}
{% block body %}
<h1>Stats Skill Challenge Page</h1>
<p>Here you will see stats of the skill in a particular challenge</p>
{% endblock %}

templates/stats/stats_skill_overall.html
{% extends 'studiocricket/base.html' %}
{% block body %}
<h1>Stats Skill Overall Page</h1>
<p>Here you will see overall stats of the skill</p>
{% endblock %}

templates/studiocricket/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<script >

</script>
</head>
<body>
	<div class="container-fluid">
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href='{% url 'home:home' %}'>Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href='{% url 'learn:learn_index' %}'>Learn</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href='{% url 'stats:stats_index' %}'>Stats</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href='#'>Tests</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href='#'>Account</a>
				</li>
			</ul>
		</div>
	</nav>
	</div>

	{% block body %}
	{% endblock %}
	

	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
</body>